name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout apollo config repo
      uses: actions/checkout@v2
      with:
        repository: apolloconfig/apollo
        path: apollo
        ref: v1.9.2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'
        distribution: 'zulu'
        cache: maven
    - run: ls -lh