name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout apollo config repo
      uses: actions/checkout@v2
      with:
        repository: apolloconfig/apollo
        path: apollo
        ref: v1.9.2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: cd apollo && ./scripts/build.sh
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: echo "${{toJSON(github)}}"
    # - name: Build and push Apollo Config Service
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     platforms: linux/amd64,linux/arm64
    #     push: true
    #     build-args: |
    #       KUBERNETES_RELEASE=${{ steps.get-latest-version.outputs.LATEST_KUBERNETES_VERSION }}
    #     tags: |
    #       ${{ secrets.DOCKERHUB_USERNAME }}/kubectl:${{ steps.get-latest-version.outputs.LATEST_KUBERNETES_VERSION }}
    #       ${{ secrets.DOCKERHUB_USERNAME }}/kubectl:latest
    - run: ls -lh