name: Docker Image CI

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout apollo config repo
      uses: actions/checkout@v2
      with:
        repository: apolloconfig/apollo
        path: apollo
        ref: v${{ github.ref_name }}
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: cd apollo && ./scripts/build.sh
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Apollo Config Service
      uses: docker/build-push-action@v2
      with:
        context: apollo/apollo-configservice/target/
        file: configservice.Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        build-args: |
          VERSION=${{ github.ref_name }}
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/apollo-config:configservice-${{ github.ref_name }}
    - name: Build and push Apollo Admin Service
      uses: docker/build-push-action@v2
      with:
        context: apollo/apollo-adminservice/target/
        file: adminservice.Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        build-args: |
          VERSION=${{ github.ref_name }}
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/apollo-config:adminservice-${{ github.ref_name }}
    - name: Build and push Apollo Portal
      uses: docker/build-push-action@v2
      with:
        context: apollo/apollo-portal/target/
        file: portal.Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        build-args: |
          VERSION=${{ github.ref_name }}
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/apollo-config:portal-${{ github.ref_name }}
