name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: ls -lh
    - name: Checkout apollo config repo
      uses: actions/checkout@v2
      with:
        repository: apolloconfig/apollo
        path: apollo
        # ref: 1.9.2
        # persist-credentials: false
    - run: ls -lh